// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReactDom = require("react-dom");
var Caml_array = require("bs-platform/lib/js/caml_array.js");
var Converter = require("./converter");

function convertPlain(prim) {
  return Converter.convertPlain(prim);
}

function s(prim) {
  return prim;
}

var testCases = [
  [
    "Simple inline CSS style",
    "<p style=\"background-color: red; font-size: 20px; font-family: 'Times New Roman, Georgia, sans-serif'\">Hello</p>",
    "<p style=ReactDOM.Style.make(~backgroundColor=\"red\", ~fontSize=\"20px\", ~fontFamily=\"'Times New Roman, Georgia, sans-serif'\", ())>{s(\"Hello\")}</p>"
  ],
  [
    "Inline CSS with base64 background image data",
    "<div style='background:url(data:image/png;base64,iVBORw0KGgoAAAA) repeat-x center;'>Hello</div>",
    "<div style=ReactDOM.Style.make(~background=\"url(data:image/png;base64,iVBORw0KGgoAAAA) repeat-x center\", ())>{s(\"Hello\")}</div>"
  ],
  [
    "P tag with text",
    "<p>Hello World!</p>",
    "<p>{s(\"Hello World!\")}</p>"
  ],
  [
    "Nested HTML",
    "<main><div><p><span>Hello</span></p></div></main>",
    "<main><div><p><span>{s(\"Hello\")}</span></p></div></main>"
  ],
  [
    "Classnames with colon",
    "<button class=\"bg-gray-800 hover:text-white focus:outline-none\"><span class=\"sr-only\">Hello</span><button>",
    "<button className=\"bg-gray-800 hover:text-white focus:outline-none\"><span className=\"sr-only\">{s(\"Hello\")}</span></button>"
  ],
  [
    "Void tags",
    "<br>",
    "<br />"
  ],
  [
    "Ignore unsupported attributes",
    "<p aria-label=\"intro\" aria-haspopup=\"true\">Hello</p>",
    "<p ariaLabel=\"intro\">{s(\"Hello\")}</p>"
  ],
  [
    "Use DOM cased attribute names",
    "<p contenteditable=\"true\">Hello</p>",
    "<p contentEditable={true}>{s(\"Hello\")}</p>"
  ],
  [
    "HTML comments",
    "<p><!-- This is a comment !-->Hello</p>",
    "<p>/* This is a comment ! */{s(\"Hello\")}</p>"
  ],
  [
    "Multi-line HTML comments",
    "<!--\n  Dropdown menu, show/hide based on menu state.\n\n  Entering: \"transition ease-out duration-100\"\n    From: \"transform opacity-0 scale-95\"\n    To: \"transform opacity-100 scale-100\"\n-->",
    "/* Dropdown menu, show/hide based on menu state.\n\n  Entering: \"transition ease-out duration-100\"\n    From: \"transform opacity-0 scale-95\"\n    To: \"transform opacity-100 scale-100\" */"
  ],
  [
    "ReScript reserved keywords",
    "<input type=\"text\" name=\"hello\" for=\"hello\" />",
    "<input type_=\"text\" name=\"hello\" htmlFor=\"hello\" />"
  ],
  [
    "SVG",
    "<svg class=\"h-6 w-6\" xmlns=\"http://www.w3.org/2000/svg\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\" aria-hidden=\"true\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M15 17h5l-1.405-1.405A2.032 2.032 0 0118 0H9\" /></svg>",
    "<svg className=\"h-6 w-6\" xmlns=\"http://www.w3.org/2000/svg\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\" ariaHidden={true}><path strokeLinecap=\"round\" strokeLinejoin=\"round\" strokeWidth=\"2\" d=\"M15 17h5l-1.405-1.405A2.032 2.032 0 0118 0H9\"></path></svg>"
  ],
  [
    "IMG with src url",
    "<img class=\"h-8 w-8 rounded-full\" src=\"https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80\" alt=\"\">",
    "<img className=\"h-8 w-8 rounded-full\" src=\"https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80\" alt=\"\" />"
  ]
];

function testResults(param) {
  return testCases.map(function ($$case, index) {
              var caseName = Caml_array.get($$case, 0);
              var inputText = Caml_array.get($$case, 1);
              var expectedOutput = Caml_array.get($$case, 2);
              var outputText = Converter.convertPlain(inputText);
              var outputText$1 = outputText.map(function (prim) {
                      return prim.trim();
                    }).join("");
              var isTestPassing = expectedOutput === outputText$1;
              var className = isTestPassing ? "test-pass" : "test-fail";
              return React.createElement("div", {
                          className: "single-test-result " + className
                        }, React.createElement("p", undefined, "# " + String(index + 1 | 0) + ". "), React.createElement("strong", undefined, caseName), React.createElement("pre", undefined, inputText), React.createElement("pre", undefined, expectedOutput), isTestPassing ? null : React.createElement("pre", undefined, outputText$1));
            });
}

function BrowserTest$App(Props) {
  var match = React.useState(function () {
        return [];
      });
  var setResult = match[1];
  React.useEffect((function () {
          Curry._1(setResult, (function (param) {
                  return testResults(undefined);
                }));
          
        }), []);
  return React.createElement("div", undefined, match[0], React.createElement("button", {
                  onClick: (function (_e) {
                      return Curry._1(setResult, (function (param) {
                                    return testResults(undefined);
                                  }));
                    })
                }, "Run tests again"));
}

var App = {
  make: BrowserTest$App
};

var root = document.querySelector("#root");

if (root == null) {
  console.log("Error: could not find react element");
} else {
  ReactDom.render(React.createElement(BrowserTest$App, {}), root);
}

exports.convertPlain = convertPlain;
exports.s = s;
exports.testCases = testCases;
exports.testResults = testResults;
exports.App = App;
/* root Not a pure module */
