// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDom from "react-dom";
import * as Renderer from "./renderer";
import * as SampleData$ReactResTest from "./SampleData.bs.js";

function renderer(prim) {
  Renderer.run(prim);
  
}

function Index$App(Props) {
  return React.createElement("main", undefined, React.createElement("div", undefined, "HTML-to-ReScript-JSX"), React.createElement("div", {
                  className: "flex"
                }, React.createElement("div", undefined, React.createElement("textarea", {
                          defaultValue: SampleData$ReactResTest.initialData,
                          id: "input",
                          style: {
                            fontFamily: "monospace",
                            height: "400px",
                            marginTop: "40px",
                            width: "400px"
                          }
                        }), React.createElement("button", {
                          onClick: (function (param) {
                              Renderer.run(null);
                              
                            })
                        }, "Convert")), React.createElement("div", undefined, React.createElement("p", {
                          id: "output"
                        }))));
}

var App = {
  make: Index$App
};

var root = document.querySelector("#root");

if (root == null) {
  console.log("Error: could not find react element");
} else {
  ReactDom.render(React.createElement(Index$App, {}), root);
}

setTimeout((function (param) {
        Renderer.run(SampleData$ReactResTest.initialData);
        
      }), 200);

export {
  renderer ,
  App ,
  
}
/* root Not a pure module */
