// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDom from "react-dom";
import * as Clipboard from "./clipboard";
import * as Converter from "./converter";
import * as SampleData$ReactResTest from "./SampleData.bs.js";

function convert(prim) {
  Converter.run();
  
}

function copyOutputToClipboard(prim) {
  Clipboard.copyOutputToClipboard();
  
}

function Index$App(Props) {
  React.useEffect(function () {
        Converter.run();
        
      });
  return React.createElement("div", undefined, React.createElement("div", {
                  className: "flex"
                }, React.createElement("div", undefined, React.createElement("textarea", {
                          defaultValue: SampleData$ReactResTest.initialData,
                          id: "inputHtml",
                          onFocus: (function ($$event) {
                              return $$event.currentTarget.select();
                            })
                        }), React.createElement("button", {
                          className: "convert",
                          onClick: (function (param) {
                              Converter.run();
                              
                            })
                        }, "Convert HTML to ReScript JSX component")), React.createElement("div", undefined, React.createElement("p", {
                          id: "outputReScript"
                        }), React.createElement("button", {
                          className: "copyToClipboard",
                          onClick: (function (param) {
                              Clipboard.copyOutputToClipboard();
                              
                            })
                        }, "Copy to clipboard"))));
}

var App = {
  make: Index$App
};

var root = document.querySelector("#root");

if (root == null) {
  console.log("Error: could not find react element");
} else {
  ReactDom.render(React.createElement(Index$App, {}), root);
}

export {
  convert ,
  copyOutputToClipboard ,
  App ,
  
}
/* root Not a pure module */
