// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var initialData = "\n<!-- Welcome! -->\n\n<main>\n  <img class=\"h-8 w-8\" src=\"logo.svg\" alt=\"Logo\">\n\n  <!-- SVG should work -->\n  <svg class=\"h-6 w-6\" xmlns=\"http://www.w3.org/2000/svg\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\" aria-hidden=\"true\">\n    <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9\" />\n  </svg>\n\n  <!-- Inline styles -->\n  <div style=\"background-color: blue; font-family: 'Arial, Times New Roman, serif;'\">\n    Hello\n  </div>\n</main>\n";

exports.initialData = initialData;
/* No side effect */
